"""Pipeline: EAL compilation (grammar-pinned), validation, mission calls."""

import easynet_sdk
import pytest
from conftest import expected_descriptor_ref
from test_client import IDENTITY, FakeTransport, ok_response  # shared fakes

from easyremote.client import Client
from easyremote.errors import InternalError, InvalidArgument
from easyremote.mission import MissionStatus
from easyremote.pipeline import MissionRun, Pipeline, StepOutput

AUTOMATION_SYSTEM_AGENT_URA = "easynet:///r/acme/agent/device.dev-a.automation"
RUNTIME_INTROSPECTION_SYSTEM_AGENT_URA = (
    "easynet:///r/acme/agent/device.dev-a.runtime-introspection"
)
RUNTIME_HEALTH_SUBJECT_URA = (
    "easynet:///r/acme/resource/device.dev-a/runtime-health"
)


def make_client(responses=None):
    transport = FakeTransport(responses=responses)
    return Client(transport=transport, identity=IDENTITY), transport


def test_two_step_mission_compiles_to_pinned_eal():
    pipe = Pipeline("nightly-report")
    fetch = pipe.step("teamA.fetch_sales", quarter="Q2", timeout=60)
    pipe.step("er.summarize", rows=fetch.output, on_failure="retry", retries=2)

    eal = pipe.to_eal()
    assert (
        'mission "nightly-report" {\n'
        '  let fetch_sales = call "teamA.fetch_sales"'
        ' with { quarter = "Q2" } timeout 60\n'
        '  let summarize = call "er.summarize"'
        " with { rows = fetch_sales.output } retries 2 on_failure retry\n"
        "}"
    ) in eal
    assert eal.startswith("// generated by easyremote")


def test_on_target_and_bool_int_rendering():
    pipe = Pipeline("p")
    pipe.step("design", on="claude", prompt="go", fast=True, n=3)
    eal = pipe.to_eal()
    assert 'call "design" on "claude"' in eal
    assert "fast = true" in eal
    assert "n = 3" in eal


def test_fractional_timeout_rounds_up_to_positive_seconds():
    pipe = Pipeline("p")
    pipe.step("er.fn", timeout=0.5)
    assert "timeout 1" in pipe.to_eal()


def test_invalid_timeout_and_retries_rejected():
    pipe = Pipeline("p")
    with pytest.raises(InvalidArgument) as exc_info:
        pipe.step("er.fn", timeout=0)
    assert exc_info.value.reason == "invalid_timeout"

    with pytest.raises(InvalidArgument) as exc_info:
        pipe.step("er.fn", retries=-1)
    assert exc_info.value.reason == "invalid_retries"


def test_non_finite_eal_number_rejected():
    pipe = Pipeline("p")
    with pytest.raises(InvalidArgument) as exc_info:
        pipe.step("er.fn", x=float("nan"))
    assert exc_info.value.reason == "non_finite_field"


def test_alias_deduplication():
    pipe = Pipeline("p")
    first = pipe.step("er.fn", a=1)
    second = pipe.step("er.fn", a=2)
    assert first.alias == "fn"
    assert second.alias == "fn_2"


def test_non_scalar_field_rejected_with_guidance():
    pipe = Pipeline("p")
    with pytest.raises(InvalidArgument) as exc_info:
        pipe.step("er.fn", payload={"nested": 1})
    assert exc_info.value.reason == "non_scalar_field"
    assert ".output" in str(exc_info.value)


def test_foreign_step_output_rejected():
    other = Pipeline("other")
    foreign = other.step("er.src")
    pipe = Pipeline("p")
    with pytest.raises(InvalidArgument, match="not part of this pipeline"):
        pipe.step("er.fn", data=foreign.output)


def test_invalid_failure_policy_rejected():
    pipe = Pipeline("p")
    with pytest.raises(InvalidArgument, match="on_failure"):
        pipe.step("er.fn", on_failure="explode")


def test_empty_pipeline_cannot_compile():
    with pytest.raises(InvalidArgument, match="no steps"):
        Pipeline("p").to_eal()


def test_step_output_render():
    assert StepOutput("fetch").render() == "fetch.output"


def test_child_invocation_intents_are_easyremote_owned():
    pipe = Pipeline("p")
    first = pipe.step("observe.health")
    pipe.step("notify.user", msg=first.output, on_failure="continue", optional=True)

    intents = pipe.child_invocation_intents()

    assert [(intent.step_id, intent.ability) for intent in intents] == [
        ("health", "observe.health"),
        ("user", "notify.user"),
    ]
    assert intents[1].optional is True


def test_pipeline_validates_daemon_child_invocation_facts():
    pipe = Pipeline("p")
    pipe.step("observe.health")
    status = MissionStatus.from_json(
        b"""{
          "profile": "mission",
          "kind": "mission_status",
          "mission_id": "run-1",
          "state": "completed",
          "terminal": true,
          "partial_failures": 0,
          "cancelled": false,
          "parent_invocation_id": "invoke-run-1",
          "parent_receipt_ura": null,
          "parent_invocation": null,
          "child_invocations": [
            {
              "step_id": "health",
              "request_id": "req-1",
              "trace_id": "run-1",
              "ability": "observe.health",
              "invocation_ura": "easynet:///r/acme/invocation/req-1",
              "caller_ura": "easynet:///r/acme/agent/device.dev-a.automation",
              "callee_ura": "easynet:///r/acme/agent/device.dev-a.runtime-introspection",
              "subject_ura": "easynet:///r/acme/resource/device.dev-a/runtime-health",
              "metadata_state": "receipt_backed",
              "ledger_state": "completed",
              "receipt": {
                "receipt_ura": "easynet:///r/acme/resource/agent.easyremote.test/invocation/r-1/receipt",
                "receipt_hash": """
        b'"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"'
        b"""
              }
            }
          ],
          "child_receipts": [],
          "output_refs": [],
          "metadata": {"profile": "mission"}
        }"""
    )

    conformance = pipe.validate_child_invocations(status)

    assert conformance.passed is True
    assert conformance.receipt_backed_steps == ("health",)


def test_mission_status_projects_child_receipt_anchor_through_sdk(monkeypatch):
    seen: list[object] = []
    original = easynet_sdk.ReceiptReference.from_runtime_receipt

    def spy(receipt: object) -> easynet_sdk.ReceiptReference:
        seen.append(receipt)
        return original(receipt)

    monkeypatch.setattr(
        easynet_sdk.ReceiptReference,
        "from_runtime_receipt",
        staticmethod(spy),
    )

    MissionStatus.from_json(
        {
            "profile": "mission",
            "kind": "mission_status",
            "mission_id": "run-1",
            "state": "completed",
            "terminal": True,
            "child_invocations": [
                {
                    "step_id": "health",
                    "request_id": "req-1",
                    "trace_id": "run-1",
                    "ability": "observe.health",
                    "invocation_ura": "easynet:///r/acme/invocation/req-1",
                    "caller_ura": AUTOMATION_SYSTEM_AGENT_URA,
                    "callee_ura": RUNTIME_INTROSPECTION_SYSTEM_AGENT_URA,
                    "subject_ura": RUNTIME_HEALTH_SUBJECT_URA,
                    "metadata_state": "receipt_backed",
                    "ledger_state": "completed",
                    "receipt": {
                        "receipt_ura": (
                            "easynet:///r/acme/resource/agent.easyremote.test"
                            "/invocation/r-1/receipt"
                        ),
                        "receipt_hash": "aa" * 32,
                    },
                }
            ],
        }
    )

    assert seen == [
        {
            "receipt_ura": (
                "easynet:///r/acme/resource/agent.easyremote.test"
                "/invocation/r-1/receipt"
            ),
            "self_hash_hex": "aa" * 32,
        }
    ]


def test_mission_status_rejects_invalid_child_receipt_anchor():
    with pytest.raises(InternalError) as exc_info:
        MissionStatus.from_json(
            {
                "profile": "mission",
                "kind": "mission_status",
                "mission_id": "run-1",
                "state": "completed",
                "terminal": True,
                "child_invocations": [
                    {
                        "step_id": "health",
                        "request_id": "req-1",
                        "trace_id": "run-1",
                        "ability": "observe.health",
                        "invocation_ura": "easynet:///r/acme/invocation/req-1",
                        "caller_ura": AUTOMATION_SYSTEM_AGENT_URA,
                        "callee_ura": RUNTIME_INTROSPECTION_SYSTEM_AGENT_URA,
                        "subject_ura": RUNTIME_HEALTH_SUBJECT_URA,
                        "metadata_state": "receipt_backed",
                        "ledger_state": "completed",
                        "receipt": {
                            "receipt_ura": "receipt-1",
                            "receipt_hash": "aa",
                        },
                    }
                ],
            }
        )
    assert exc_info.value.reason == "invalid_mission_status"


def test_mission_status_rejects_duplicate_child_step_facts():
    child = {
        "step_id": "health",
        "request_id": "req-1",
        "trace_id": "run-1",
        "ability": "observe.health",
        "invocation_ura": "easynet:///r/acme/invocation/req-1",
        "caller_ura": AUTOMATION_SYSTEM_AGENT_URA,
        "callee_ura": RUNTIME_INTROSPECTION_SYSTEM_AGENT_URA,
        "subject_ura": RUNTIME_HEALTH_SUBJECT_URA,
        "metadata_state": "running",
        "ledger_state": "running",
        "receipt": None,
    }

    with pytest.raises(InternalError) as exc_info:
        MissionStatus.from_json(
            {
                "profile": "mission",
                "kind": "mission_status",
                "mission_id": "run-1",
                "state": "running",
                "terminal": False,
                "child_invocations": [child, dict(child, request_id="req-2")],
            }
        )
    assert exc_info.value.reason == "invalid_mission_status"


def test_created_by_header_uses_identity():
    client, _ = make_client()
    pipe = Pipeline("p", client=client)
    pipe.step("er.fn", a=1)
    assert "// created_by: easynet:///r/acme/user/silan" in pipe.to_eal()


def test_run_submits_source_to_mission_run():
    client, transport = make_client(
        responses=[
            ok_response(
                {"ok": True, "run_id": "run-1", "run_dir": "/tmp/r", "outputs": {}}
            )
        ]
    )
    pipe = Pipeline("nightly", client=client)
    pipe.step("er.fn", a=1)

    run = pipe.run()
    wire = transport.invocations[0]
    assert transport.carriers == ["runtime"]
    assert wire["descriptor_ref"] == expected_descriptor_ref(
        "easynet:///r/acme/ability/system-agent.dev-a.automation.mission.run"
    )
    assert wire["args"]["label"] == "nightly"
    assert 'mission "nightly"' in wire["args"]["source"]
    assert run.run_id == "run-1"


def test_track_and_cancel_use_run_id():
    client, transport = make_client(
        responses=[
            ok_response({"ok": True, "run_id": "run-9"}),
            ok_response({"state": "running"}),
            ok_response({"cancelled": True}),
        ]
    )
    pipe = Pipeline("p", client=client)
    pipe.step("er.fn")
    run = pipe.run()

    assert run.track() == {"state": "running"}
    run.cancel()
    assert transport.carriers == ["runtime", "runtime", "runtime"]
    assert transport.invocations[1]["descriptor_ref"] == expected_descriptor_ref(
        "easynet:///r/acme/ability/system-agent.dev-a.automation.mission.track"
    )
    assert transport.invocations[1]["args"] == {"run_id": "run-9"}
    assert transport.invocations[2]["descriptor_ref"] == expected_descriptor_ref(
        "easynet:///r/acme/ability/system-agent.dev-a.automation.mission.cancel"
    )


def test_pipeline_run_handle_fetches_events():
    client, transport = make_client(
        responses=[
            ok_response({"ok": True, "run_id": "run-9"}),
            ok_response(
                {
                    "cursor_sequence": 0,
                    "next_cursor_sequence": 1,
                    "has_more": False,
                    "dropped_count": 0,
                    "events": [
                        {
                            "sequence": 0,
                            "event_type": "completed",
                            "occurred_unix_ms": 1_700_000_000_000,
                            "terminal": True,
                            "payload": {"reply": "done"},
                        }
                    ],
                }
            ),
        ]
    )
    pipe = Pipeline("p", client=client)
    pipe.step("er.fn")
    run = pipe.run()

    page = run.events()

    assert page["events"][0]["payload"] == {"reply": "done"}
    assert transport.carriers == ["runtime", "runtime"]
    assert transport.invocations[1]["descriptor_ref"] == expected_descriptor_ref(
        "easynet:///r/acme/ability/system-agent.dev-a.automation.mission.events"
    )


def test_pipeline_run_handle_tails_events_until_terminal():
    client, transport = make_client(
        responses=[
            ok_response({"ok": True, "run_id": "run-9"}),
            ok_response(
                {
                    "cursor_sequence": 0,
                    "next_cursor_sequence": 1,
                    "has_more": True,
                    "dropped_count": 0,
                    "events": [
                        {
                            "sequence": 0,
                            "event_type": "progress",
                            "occurred_unix_ms": 1_700_000_000_000,
                            "terminal": False,
                            "payload": {"step": "fetch"},
                            "receipt": {},
                            "metadata": {"step_id": "fetch"},
                        }
                    ],
                }
            ),
            ok_response(
                {
                    "cursor_sequence": 1,
                    "next_cursor_sequence": 2,
                    "has_more": False,
                    "dropped_count": 0,
                    "events": [
                        {
                            "sequence": 1,
                            "event_type": "completed",
                            "occurred_unix_ms": 1_700_000_000_001,
                            "terminal": True,
                            "payload": {"reply": "done"},
                            "receipt": {
                                "receipt_ura": "easynet:///r/acme/resource/agent.easyremote.test/invocation/r-1/receipt"
                            },
                            "metadata": {},
                        }
                    ],
                }
            ),
        ]
    )
    pipe = Pipeline("p", client=client)
    pipe.step("er.fn")
    run = pipe.run()

    events = list(run.tail_events(limit=1))

    assert [event["event_type"] for event in events] == ["progress", "completed"]
    assert events[1]["payload"] == {"reply": "done"}
    assert transport.carriers == ["runtime", "runtime", "runtime"]
    assert transport.invocations[1]["args"] == {
        "run_id": "run-9",
        "cursor_sequence": 0,
        "limit": 1,
    }
    assert transport.invocations[2]["args"] == {
        "run_id": "run-9",
        "cursor_sequence": 1,
        "limit": 1,
    }


def test_mission_run_exposes_response_fields():
    client, _ = make_client()
    run = MissionRun(
        client.missions,
        {"run_id": "r", "run_dir": "/d", "outputs": {"x": 1}},
    )
    assert run.run_dir == "/d"
    assert run.outputs == {"x": 1}
