"""Pipeline: EAL compilation (grammar-pinned), validation, mission calls."""

import pytest
from test_client import IDENTITY, FakeTransport, ok_response  # shared fakes

from easyremote.client import Client
from easyremote.errors import InvalidArgument
from easyremote.pipeline import MissionRun, Pipeline, StepOutput


def make_client(responses=None):
    transport = FakeTransport(responses=responses)
    return Client(transport=transport, identity=IDENTITY), transport


def test_two_step_mission_compiles_to_pinned_eal():
    pipe = Pipeline("nightly-report")
    fetch = pipe.step("teamA.fetch_sales", quarter="Q2", timeout=60)
    pipe.step("er.summarize", rows=fetch.output, on_failure="retry", retries=2)

    eal = pipe.to_eal()
    assert (
        'mission "nightly-report" {\n'
        '  let fetch_sales = call "teamA.fetch_sales"'
        ' with { quarter = "Q2" } timeout 60\n'
        '  let summarize = call "er.summarize"'
        " with { rows = fetch_sales.output } retries 2 on_failure retry\n"
        "}"
    ) in eal
    assert eal.startswith("// generated by easyremote")


def test_on_target_and_bool_int_rendering():
    pipe = Pipeline("p")
    pipe.step("design", on="claude", prompt="go", fast=True, n=3)
    eal = pipe.to_eal()
    assert 'call "design" on "claude"' in eal
    assert "fast = true" in eal
    assert "n = 3" in eal


def test_fractional_timeout_rounds_up_to_positive_seconds():
    pipe = Pipeline("p")
    pipe.step("er.fn", timeout=0.5)
    assert "timeout 1" in pipe.to_eal()


def test_invalid_timeout_and_retries_rejected():
    pipe = Pipeline("p")
    with pytest.raises(InvalidArgument) as exc_info:
        pipe.step("er.fn", timeout=0)
    assert exc_info.value.reason == "invalid_timeout"

    with pytest.raises(InvalidArgument) as exc_info:
        pipe.step("er.fn", retries=-1)
    assert exc_info.value.reason == "invalid_retries"


def test_non_finite_eal_number_rejected():
    pipe = Pipeline("p")
    with pytest.raises(InvalidArgument) as exc_info:
        pipe.step("er.fn", x=float("nan"))
    assert exc_info.value.reason == "non_finite_field"


def test_alias_deduplication():
    pipe = Pipeline("p")
    first = pipe.step("er.fn", a=1)
    second = pipe.step("er.fn", a=2)
    assert first.alias == "fn"
    assert second.alias == "fn_2"


def test_non_scalar_field_rejected_with_guidance():
    pipe = Pipeline("p")
    with pytest.raises(InvalidArgument) as exc_info:
        pipe.step("er.fn", payload={"nested": 1})
    assert exc_info.value.reason == "non_scalar_field"
    assert ".output" in str(exc_info.value)


def test_foreign_step_output_rejected():
    other = Pipeline("other")
    foreign = other.step("er.src")
    pipe = Pipeline("p")
    with pytest.raises(InvalidArgument, match="not part of this pipeline"):
        pipe.step("er.fn", data=foreign.output)


def test_invalid_failure_policy_rejected():
    pipe = Pipeline("p")
    with pytest.raises(InvalidArgument, match="on_failure"):
        pipe.step("er.fn", on_failure="explode")


def test_empty_pipeline_cannot_compile():
    with pytest.raises(InvalidArgument, match="no steps"):
        Pipeline("p").to_eal()


def test_step_output_render():
    assert StepOutput("fetch").render() == "fetch.output"


def test_created_by_header_uses_identity():
    client, _ = make_client()
    pipe = Pipeline("p", client=client)
    pipe.step("er.fn", a=1)
    assert "// created_by: easynet:///r/acme/device/dev-a" in pipe.to_eal()


def test_run_submits_source_to_mission_run():
    client, transport = make_client(
        responses=[
            ok_response(
                {"ok": True, "run_id": "run-1", "run_dir": "/tmp/r", "outputs": {}}
            )
        ]
    )
    pipe = Pipeline("nightly", client=client)
    pipe.step("er.fn", a=1)

    run = pipe.run()
    wire = transport.invocations[0]
    assert transport.carriers == ["unary"]
    assert (
        wire["descriptor_ref"]
        == "easynet:///r/acme/ability/device.dev-a.mission.run@1.0.0"
    )
    assert wire["args"]["label"] == "nightly"
    assert 'mission "nightly"' in wire["args"]["source"]
    assert run.run_id == "run-1"


def test_track_and_cancel_use_run_id():
    client, transport = make_client(
        responses=[
            ok_response({"ok": True, "run_id": "run-9"}),
            ok_response({"state": "running"}),
            ok_response({"cancelled": True}),
        ]
    )
    pipe = Pipeline("p", client=client)
    pipe.step("er.fn")
    run = pipe.run()

    assert run.track() == {"state": "running"}
    run.cancel()
    assert transport.carriers == ["unary", "unary", "unary"]
    assert (
        transport.invocations[1]["descriptor_ref"]
        == "easynet:///r/acme/ability/device.dev-a.mission.track@1.0.0"
    )
    assert transport.invocations[1]["args"] == {"run_id": "run-9"}
    assert (
        transport.invocations[2]["descriptor_ref"]
        == "easynet:///r/acme/ability/device.dev-a.mission.cancel@1.0.0"
    )


def test_mission_run_exposes_response_fields():
    client, _ = make_client()
    run = MissionRun(
        client.missions,
        {"run_id": "r", "run_dir": "/d", "outputs": {"x": 1}},
    )
    assert run.run_dir == "/d"
    assert run.outputs == {"x": 1}
