"""EasyRemote Pipeline: an acyclic product plan compiled to daemon EAL."""

from __future__ import annotations

import json
import math
import re
from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

from ._version import __version__
from .errors import InternalError, InvalidArgument
from .mission import MissionChildInvocation, MissionControl, MissionRun, MissionStatus
from .node import RegisteredFunction

if TYPE_CHECKING:
    from .client import Client

__all__ = [
    "MissionChildInvocationConformance",
    "MissionChildInvocationIntent",
    "MissionRun",
    "Pipeline",
    "Step",
    "StepOutput",
]

_FAILURE_POLICIES = frozenset({"abort", "skip", "retry", "continue"})
_IDENTIFIER = re.compile(r"[^A-Za-z0-9_]")


@dataclass(frozen=True)
class StepOutput:
    """A dataflow reference to one earlier step result."""

    alias: str

    def render(self) -> str:
        return f"{self.alias}.output"


@dataclass(frozen=True)
class Step:
    alias: str
    ref: str
    args: Mapping[str, object]
    on: str | None = None
    timeout: int | None = None
    retries: int | None = None
    on_failure: str | None = None
    optional: bool = False

    @property
    def output(self) -> StepOutput:
        return StepOutput(self.alias)

    def render(self) -> str:
        parts = [f"let {self.alias} = call {_eal_string(self.ref)}"]
        if self.on:
            parts.append(f"on {_eal_string(self.on)}")
        if self.args:
            fields = ", ".join(
                f"{name} = {_eal_value(value)}" for name, value in self.args.items()
            )
            parts.append(f"with {{ {fields} }}")
        if self.timeout is not None:
            parts.append(f"timeout {self.timeout}")
        if self.retries is not None:
            parts.append(f"retries {self.retries}")
        if self.on_failure is not None:
            parts.append(f"on_failure {self.on_failure}")
        if self.optional:
            parts.append("optional")
        return " ".join(parts)


@dataclass(frozen=True)
class MissionChildInvocationIntent:
    step_id: str
    ability: str
    on: str | None
    optional: bool
    on_failure: str | None


@dataclass(frozen=True)
class MissionChildInvocationConformance:
    mission_id: str
    expected_steps: tuple[str, ...]
    observed_steps: tuple[str, ...]
    missing_steps: tuple[str, ...]
    unexpected_steps: tuple[str, ...]
    ability_mismatched_steps: tuple[str, ...]
    incomplete_fact_steps: tuple[str, ...]
    receipt_backed_steps: tuple[str, ...]

    @property
    def passed(self) -> bool:
        return not any(
            (
                self.missing_steps,
                self.unexpected_steps,
                self.ability_mismatched_steps,
                self.incomplete_fact_steps,
            )
        )

    def require_passed(self) -> None:
        if not self.passed:
            raise InternalError(
                "Mission child Invocation facts do not match the Pipeline",
                reason="mission_child_invocation_mismatch",
            )


@dataclass
class Pipeline:
    """Append-only plan; earlier-step outputs are its only dependency edges."""

    name: str
    client: Client | None = None
    _steps: list[Step] = field(init=False, repr=False, default_factory=list)
    _aliases: set[str] = field(init=False, repr=False, default_factory=set)

    def __post_init__(self) -> None:
        self.name = _text(self.name, "pipeline name", "empty_name")

    @property
    def steps(self) -> tuple[Step, ...]:
        return tuple(self._steps)

    def step(
        self,
        target: str | RegisteredFunction,
        *,
        on: str | None = None,
        timeout: float | None = None,
        retries: int | None = None,
        on_failure: str | None = None,
        optional: bool = False,
        **args: Any,
    ) -> Step:
        ref = self._target_ref(target)
        if on_failure is not None and on_failure not in _FAILURE_POLICIES:
            raise InvalidArgument(
                f"on_failure must be one of {sorted(_FAILURE_POLICIES)},"
                f" got {on_failure!r}",
                reason="invalid_failure_policy",
            )
        for name, value in args.items():
            _validate_field(name, value, self._aliases)
        step = Step(
            alias=self._fresh_alias(ref),
            ref=ref,
            args=dict(args),
            on=on.strip() if isinstance(on, str) and on.strip() else None,
            timeout=_timeout(timeout),
            retries=_retries(retries),
            on_failure=on_failure,
            optional=optional,
        )
        self._steps.append(step)
        self._aliases.add(step.alias)
        return step

    def to_eal(self) -> str:
        if not self._steps:
            raise InvalidArgument(
                f"pipeline '{self.name}' has no steps",
                reason="empty_pipeline",
            )
        lines = [f"// generated by easyremote {__version__}"]
        created_by = self._created_by()
        if created_by:
            lines.append(f"// created_by: {created_by}")
        lines.append(f"mission {_eal_string(self.name)} {{")
        lines.extend(f"  {step.render()}" for step in self._steps)
        lines.append("}")
        return "\n".join(lines) + "\n"

    def run(self, *, label: str | None = None) -> MissionRun:
        return MissionControl(self.client).run_eal(
            self.to_eal(),
            label=label or self.name,
        )

    def child_invocation_intents(
        self,
    ) -> tuple[MissionChildInvocationIntent, ...]:
        return tuple(
            MissionChildInvocationIntent(
                step.alias,
                step.ref,
                step.on,
                step.optional,
                step.on_failure,
            )
            for step in self._steps
        )

    def validate_child_invocations(
        self,
        status: MissionStatus | Mapping[str, object],
    ) -> MissionChildInvocationConformance:
        projected = (
            status
            if isinstance(status, MissionStatus)
            else MissionStatus.from_json(status)
        )
        expected = {item.step_id: item for item in self.child_invocation_intents()}
        observed = {item.step_id: item for item in projected.child_invocations}
        expected_ids, observed_ids = set(expected), set(observed)
        result = MissionChildInvocationConformance(
            mission_id=projected.mission_id,
            expected_steps=tuple(sorted(expected_ids)),
            observed_steps=tuple(sorted(observed_ids)),
            missing_steps=tuple(sorted(expected_ids - observed_ids)),
            unexpected_steps=tuple(sorted(observed_ids - expected_ids)),
            ability_mismatched_steps=tuple(
                sorted(
                    step_id
                    for step_id in expected_ids & observed_ids
                    if expected[step_id].ability != observed[step_id].ability
                )
            ),
            incomplete_fact_steps=tuple(
                sorted(
                    step_id
                    for step_id in expected_ids & observed_ids
                    if not _child_complete(observed[step_id])
                )
            ),
            receipt_backed_steps=tuple(
                sorted(
                    item.step_id
                    for item in projected.child_invocations
                    if item.step_id in expected_ids and item.receipt is not None
                )
            ),
        )
        result.require_passed()
        return result

    def _target_ref(self, target: str | RegisteredFunction) -> str:
        value = (
            target.qualified_name if isinstance(target, RegisteredFunction) else target
        )
        if isinstance(value, str) and value.strip():
            return value.strip()
        raise InvalidArgument(
            "step target must be a qualified ability name or RegisteredFunction",
            reason="invalid_step_target",
        )

    def _fresh_alias(self, ref: str) -> str:
        base = _IDENTIFIER.sub("_", ref.rsplit(".", 1)[-1]) or "step"
        alias, counter = base, 2
        while alias in self._aliases:
            alias, counter = f"{base}_{counter}", counter + 1
        return alias

    def _created_by(self) -> str:
        if self.client is None:
            return ""
        try:
            value = self.client._who().user_ura
            return value if isinstance(value, str) else ""
        except Exception:
            return ""


def _text(value: str, label: str, reason: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise InvalidArgument(f"{label} must not be empty", reason=reason)
    return value.strip()


def _validate_field(name: str, value: object, aliases: set[str]) -> None:
    _text(name, "field name", "invalid_field_name")
    if isinstance(value, StepOutput):
        if value.alias not in aliases:
            raise InvalidArgument(
                f"step '{value.alias}' is not part of this pipeline",
                reason="foreign_step_output",
            )
        return
    if isinstance(value, bool | str | int):
        return
    if isinstance(value, float) and math.isfinite(value):
        return
    reason = "non_finite_field" if isinstance(value, float) else "non_scalar_field"
    message = (
        "EAL numbers must be finite"
        if reason == "non_finite_field"
        else "EAL field values are scalars or step outputs; reference .output"
    )
    raise InvalidArgument(message, reason=reason)


def _timeout(value: float | None) -> int | None:
    if value is None:
        return None
    if (
        not isinstance(value, int | float)
        or isinstance(value, bool)
        or not math.isfinite(value)
        or value <= 0
    ):
        raise InvalidArgument(
            "timeout must be positive and finite", reason="invalid_timeout"
        )
    return max(1, math.ceil(value))


def _retries(value: int | None) -> int | None:
    if value is None:
        return None
    if not isinstance(value, int) or isinstance(value, bool) or value < 0:
        raise InvalidArgument("retries must be non-negative", reason="invalid_retries")
    return value


def _eal_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _eal_value(value: object) -> str:
    if isinstance(value, StepOutput):
        return value.render()
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int | float):
        return repr(value)
    if isinstance(value, str):
        return _eal_string(value)
    raise InvalidArgument("unsupported EAL value", reason="non_scalar_field")


def _child_complete(child: MissionChildInvocation) -> bool:
    return (
        all(
            (
                child.step_id,
                child.request_id,
                child.trace_id,
                child.ability,
                child.invocation_ura,
                child.caller_ura,
                child.callee_ura,
                child.subject_ura,
                child.metadata_state,
            )
        )
        and child.ledger_state is not None
    )
