"""Pipeline → EAL → ``mission.run`` (SPEC §5.9; grammar-verified).

EAL's dependency edges are **dataflow only**: a later step references
an earlier one as ``alias.output``, and the daemon's planner derives
the phase DAG from those references (eal-grammar.md — there is no
standalone "after" syntax, which is why this API has no ``after=``
parameter: ordering *is* data).

Grammar limits honored at build time, not at run time:

- field values are scalars (string/int/float/bool) or step refs —
  nested objects/lists are rejected with guidance;
- failure policies are ``abort | skip | retry | continue``.

The facade compiles; the daemon executes (``mission.run`` →
``{ok, run_id, run_dir, outputs, meta}``, ``mission.track`` /
``mission.cancel`` take ``{run_id}``). No second orchestration
runtime lives here.

Provenance: the generated source carries a ``created_by`` comment
header when the client identity is available; the *structured*
provenance contract for EAL artifacts is a flagged P0 item.
"""

from __future__ import annotations

import json
import math
import re
from dataclasses import dataclass, field
from typing import Any, cast

from ._version import __version__
from .client import Client
from .errors import InvalidArgument
from .node import RegisteredFunction

__all__ = ["MissionRun", "Pipeline", "Step", "StepOutput"]

_FAILURE_POLICIES = frozenset({"abort", "skip", "retry", "continue"})
_IDENTIFIER = re.compile(r"[^A-Za-z0-9_]")


@dataclass(frozen=True)
class StepOutput:
    """A dataflow reference to one step's captured result."""

    alias: str

    def render(self) -> str:
        return f"{self.alias}.output"


@dataclass(frozen=True)
class Step:
    """One ``call`` statement; construct via :meth:`Pipeline.step` only."""

    alias: str
    ref: str
    args: dict[str, Any]
    on: str | None
    timeout: int | None
    retries: int | None
    on_failure: str | None
    optional: bool

    @property
    def output(self) -> StepOutput:
        return StepOutput(self.alias)

    def render(self) -> str:
        parts = [f"let {self.alias} = call {_string(self.ref)}"]
        if self.on:
            parts.append(f"on {_string(self.on)}")
        if self.args:
            fields = ", ".join(
                f"{name} = {_field_value(value)}" for name, value in self.args.items()
            )
            parts.append(f"with {{ {fields} }}")
        if self.timeout is not None:
            parts.append(f"timeout {self.timeout}")
        if self.retries is not None:
            parts.append(f"retries {self.retries}")
        if self.on_failure is not None:
            parts.append(f"on_failure {self.on_failure}")
        if self.optional:
            parts.append("optional")
        return " ".join(parts)


@dataclass
class Pipeline:
    """A mission under construction.

    Cycles are impossible by construction: a step can only reference
    the outputs of steps that already exist.
    """

    name: str
    client: Client | None = None
    _steps: list[Step] = field(default_factory=list, init=False, repr=False)
    _aliases: set[str] = field(default_factory=set, init=False, repr=False)

    def __post_init__(self) -> None:
        if not self.name.strip():
            raise InvalidArgument(
                "pipeline name must not be empty", reason="empty_name"
            )

    def step(
        self,
        target: str | RegisteredFunction,
        *,
        on: str | None = None,
        timeout: float | None = None,
        retries: int | None = None,
        on_failure: str | None = None,
        optional: bool = False,
        **args: Any,
    ) -> Step:
        """Append one call; pass upstream results as ``other.output``."""
        ref = self._target_ref(target)
        if on_failure is not None and on_failure not in _FAILURE_POLICIES:
            raise InvalidArgument(
                f"on_failure must be one of {sorted(_FAILURE_POLICIES)},"
                f" got {on_failure!r}",
                reason="invalid_failure_policy",
            )
        timeout_seconds = _timeout_seconds(timeout)
        retries_count = _retries_count(retries)
        for name, value in args.items():
            self._validate_field(name, value)
        step = Step(
            alias=self._fresh_alias(ref),
            ref=ref,
            args=dict(args),
            on=on,
            timeout=timeout_seconds,
            retries=retries_count,
            on_failure=on_failure,
            optional=optional,
        )
        self._steps.append(step)
        self._aliases.add(step.alias)
        return step

    def to_eal(self) -> str:
        """The mission source — inspectable before anything runs."""
        if not self._steps:
            raise InvalidArgument(
                f"pipeline '{self.name}' has no steps", reason="empty_pipeline"
            )
        lines = [f"// generated by easyremote {__version__}"]
        created_by = self._created_by()
        if created_by:
            # Structured EAL provenance is a flagged P0 contract; the
            # comment header records authorship until it lands.
            lines.append(f"// created_by: {created_by}")
        lines.append(f"mission {_string(self.name)} {{")
        lines.extend(f"  {step.render()}" for step in self._steps)
        lines.append("}")
        return "\n".join(lines) + "\n"

    def run(self, *, label: str | None = None) -> MissionRun:
        client = self.client or Client()
        response = client.execute(
            "mission.run", source=self.to_eal(), label=label or self.name
        )
        return MissionRun(client, response or {})

    # -- internals -----------------------------------------------------------

    def _target_ref(self, target: str | RegisteredFunction) -> str:
        if isinstance(target, RegisteredFunction):
            return target.qualified_name
        if isinstance(target, str) and target.strip():
            return target.strip()
        raise InvalidArgument(
            "step target must be a qualified ability name (str) or a"
            f" RegisteredFunction, got {type(target).__name__}",
            reason="invalid_step_target",
        )

    def _validate_field(self, name: str, value: Any) -> None:
        if isinstance(value, StepOutput):
            if value.alias not in self._aliases:
                raise InvalidArgument(
                    f"argument '{name}' references step '{value.alias}', which is"
                    " not part of this pipeline",
                    reason="foreign_step_output",
                )
            return
        if isinstance(value, bool | str | int):
            return
        if isinstance(value, float):
            if math.isfinite(value):
                return
            raise InvalidArgument(
                f"argument '{name}' is non-finite ({value!r}); EAL numbers must"
                " be finite",
                reason="non_finite_field",
            )
        raise InvalidArgument(
            f"argument '{name}' is {type(value).__name__} — EAL field values are"
            " scalars or step outputs; pass structured data through an ability"
            " that returns it, then reference its .output",
            reason="non_scalar_field",
        )

    def _fresh_alias(self, ref: str) -> str:
        base = _IDENTIFIER.sub("_", ref.rsplit(".", 1)[-1]) or "step"
        alias = base
        counter = 2
        while alias in self._aliases:
            alias = f"{base}_{counter}"
            counter += 1
        return alias

    def _created_by(self) -> str:
        if self.client is None:
            return ""
        try:
            return self.client._who().device_ura
        except Exception:  # identity not paired yet — header is optional
            return ""


class MissionRun:
    """Handle for a submitted mission (``mission.run`` response)."""

    def __init__(self, client: Client, response: dict[str, Any]) -> None:
        self._client = client
        self._response = response

    @property
    def run_id(self) -> str:
        return str(self._response.get("run_id", ""))

    @property
    def run_dir(self) -> str:
        return str(self._response.get("run_dir", ""))

    @property
    def outputs(self) -> dict[str, Any]:
        return dict(self._response.get("outputs") or {})

    @property
    def raw(self) -> dict[str, Any]:
        return self._response

    def track(self) -> dict[str, Any]:
        return cast(
            "dict[str, Any]", self._client.execute("mission.track", run_id=self.run_id)
        )

    @property
    def status(self) -> dict[str, Any]:
        return self.track()

    def cancel(self) -> dict[str, Any]:
        return cast(
            "dict[str, Any]", self._client.execute("mission.cancel", run_id=self.run_id)
        )


def _string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _field_value(value: Any) -> str:
    if isinstance(value, StepOutput):
        return value.render()
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return repr(value)
    if isinstance(value, float):
        if not math.isfinite(value):
            raise InvalidArgument(
                f"EAL number must be finite, got {value!r}",
                reason="non_finite_field",
            )
        return repr(value)
    return _string(value)


def _timeout_seconds(timeout: float | None) -> int | None:
    if timeout is None:
        return None
    if not math.isfinite(timeout) or timeout <= 0:
        raise InvalidArgument(
            f"timeout must be a positive finite number of seconds, got {timeout!r}",
            reason="invalid_timeout",
        )
    return max(1, math.ceil(timeout))


def _retries_count(retries: int | None) -> int | None:
    if retries is None:
        return None
    if retries < 0:
        raise InvalidArgument(
            f"retries must be non-negative, got {retries}",
            reason="invalid_retries",
        )
    return retries
